Big integer was implemented
TopCoder2K/Cpp-homework pull request #30
Opened 2019-12-18 16:32 UTC by TopCoder2K

4_1

2019-12-19 21:43 UTC, Ya-Egor requested changes
Как-то много потенциальных косяков. Надо добавить больше тестов на знаки и длинное умножение  и заслать в контест, чтобы там тесты прошли.

2019-12-19 21:43 UTC, Ya-Egor commented on 3semester/4contest/BigInteger/biginteger.h
> +std::vector<char> BigInteger::pop_front_(const std::vector<char>& to_shift) {
Зачем делать копию? Можно было бы inplace всё сделать

2019-12-19 21:43 UTC, Ya-Egor commented on 3semester/4contest/BigInteger/biginteger.h
> +        shifted.digits_[shift + i] = to_shift.digits_[i];
А что в конце будет лежать по индексам 0..shift-1 ? Если ты думаешь, что 0 - это не так.

2019-12-19 21:43 UTC, Ya-Egor commented on 3semester/4contest/BigInteger/biginteger.h
> +    }
0 / -1 == -0 ?

2019-12-19 21:43 UTC, Ya-Egor commented on 3semester/4contest/BigInteger/biginteger.h
> +    BigInteger tmp = other;
тут negative == negative_ || other.negative_ или неопределено, если !negative_ && !other.negative_

2019-12-21 11:58 UTC, TopCoder2K commented on 3semester/4contest/BigInteger/biginteger.h
> +    }
-0 учитывается при выводе, а в работе никак не мешает.

2019-12-21 12:10 UTC, TopCoder2K commented on 3semester/4contest/BigInteger/biginteger.h
> +        shifted.digits_[shift + i] = to_shift.digits_[i];
Как не 0 будет? Там же resize с нулевого размера + заполнение 0. Эта функция нужна для того, чтобы 0 добавлять

2019-12-21 12:16 UTC, TopCoder2K commented on 3semester/4contest/BigInteger/biginteger.h
> +std::vector<char> BigInteger::pop_front_(const std::vector<char>& to_shift) {
Да, есть же метод erase

2019-12-21 12:22 UTC, TopCoder2K commented on 3semester/4contest/BigInteger/biginteger.h
> +    BigInteger tmp = other;
Как не определено? Если !negative_ && !other.negative_, то заходит в else, тогда negative = true || true, что есть true

2019-12-22 05:20 UTC, Ya-Egor commented on 3semester/4contest/BigInteger/biginteger.h
> +        shifted.digits_[shift + i] = to_shift.digits_[i];
Ок. Кстати, а почему это статический метод, а не константный метод класса?

2019-12-22 05:22 UTC, Ya-Egor commented on 3semester/4contest/BigInteger/biginteger.h
> +    BigInteger tmp = other;
Да, точно. Но всё равно, переменная без инициализатора - потенциальное место для граблей. Лучше сразу написать bool negative = negative_ || other.negative_;

2019-12-22 05:26 UTC, Ya-Egor commented on 3semester/4contest/BigInteger/biginteger.h
> +    if (*this == 0) {
А почему не if(*this) ?

2019-12-22 05:26 UTC, Ya-Egor approved these changes

2019-12-22 06:59 UTC, TopCoder2K commented on 3semester/4contest/BigInteger/biginteger.h
> +    BigInteger tmp = other;
Ну это да, я за этим стараюсь следить

2019-12-22 07:00 UTC, TopCoder2K commented on 3semester/4contest/BigInteger/biginteger.h
> +    if (*this == 0) {
Вот тут вопрос. Стоит ли для наглядности делать так, как я? Или вполне вариант if(*this) хорош?

2019-12-22 07:01 UTC, TopCoder2K commented on 3semester/4contest/BigInteger/biginteger.h
> +        shifted.digits_[shift + i] = to_shift.digits_[i];
Потому что он не привязан к конкретному объекту типа этого класса. Это вспомогательная функция

2019-12-31 12:44 UTC, merged