Debug
TopCoder2K/Cpp-homework pull request #7
Opened 2019-09-29 12:39 UTC by TopCoder2K

Now it's correct. First 3 tasks were added.

2019-09-29 16:19 UTC, Mrkol requested changes

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +/*
Отдельные пулл-реквесты на все 3 задачи пожалуйста.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +        }
Выглядит уродливо

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +        alphabet[static_cast<int32_t>(answer[position]) - 97] = false;
Что за магическое число 97

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +    int32_t position = prefix_fuc.size() > 1 ? prefix_fuc[prefix_fuc.size() - 2] : -1;
Зачем такие сложные костыли когда можно в начале функции написать assert(prefix_func.size() > 0); if (prefix_func.size() == 1) return 'a'; или что-то вроде того?

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +char AddCharacter(std::string& answer, const std::vector<int32_t>& prefix_fuc) {
const std::string& answer, ты ж его не меняешь.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +    std::vector<bool> alphabet(26,true);
У тебя размер алфавита статически задаётся, поэтому можно использовать std::bitset. Лишние аллокации на куче -- не есть хорошо.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +    }
Это весьма полезное действие, заслуживающее отдельной функции а ля MostSignificantBit или CountLeadingZeros. Плюс в общем случае его можно на порядок ускорить если залезть в реализацию std::vector<bool>/std::bitset, но это уже совсем отдельный разговор.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +void ReconstructionByPrefix(std::string& answer) {
Зачем возвращать строки через аргумент-ссылку, когда есть return value optimization?
И вообще какая-то идиотская функция, она кагбэ за ввод отвечает, но за вывод -- нет. Сделай штуку, которая будет принимать пару итераторов на начало-конец префикс функции, а внутрь неё передавай std::istream_iterator<int>(std::cin), std::istream_iterator<int>().

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +    while(std::cin >> cur_value && cur_value != -1) {
Кажется, тебе никто -1 в этой задаче не передаёт на вход. Зачем это условие тут?

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +    std::vector<int32_t> prefix_fuc;
Не лучший выбор названия переменной, особенно для ревью

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +            answer.push_back(AddCharacter(answer, prefix_fuc));
Твоя функция AddCharacter не добавляет букву. Название такое себе.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +    ~Node() = default;
Зочем?!

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +char AddCharacter(const std::unordered_set<char>& forbidden_chars) {
Почему раньше вектор булов юзал, а теперь unordered_set? std::bitset у тебя всего 8 байт на стеке займёт, а это чудо займёт чёрт знает сколько и работать будет скорее всего дольше. 

И эта функция опять же не добавляет никаких букв. Очень плохой нейминг.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +            return static_cast<char>(i + 97);
Магическое число 97 такое магическое.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +    return 'z';
assert(false, "vse ploho") или throw std::runtime_error("ne validnaya z-funkcia((((99");

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +void ReconstructionByZ(std::vector<Node>& answer) {
Ну совсем идиотский интерфейс подъехал. Твой класс Node -- детали имплементации. Какого чёрта человек, захотевший посчитать по z-функции строку должен знать о том, какие ты там std::unordered_set'ы и Node'ы юзаешь? Функция должна принимать z-функцию в каком-то виде и возвращать строку в каком-то виде.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +class Node {
Node -- очень странное имя для этого класса.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +    int32_t cur_z_value = 0, prefix_length = 0, prefix_remaining_length = 0;
За объявления переменных через запятую бан.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +    answer[0].character = 'a';
Тебе кинули пустой answer, ты проиграл.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +    std::cin >> cur_z_value;
Опять же, чому функция вводит, считает ответ, но не выводит? Где логика в разделении обязанностей в твоём коде?

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +            answer[counter] = answer[prefix_length - prefix_remaining_length];
Чево. Почему не просто answer[counter] = answer[0]?

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +        ++counter;
"Счётчик" -- плохое название переменной.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +            }
В целом очень сложный код. Попробуй сделать его проще/читабильнее.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +    int32_t str_size = 1000;
БАН

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +    int32_t n = s.size(), j = 0;
бан

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +std::vector<int32_t> CalcPrefixFunc(std::string& s) {
const бан

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +    std::vector<int32_t> prefix_func(n, 0);
для размеров используем тип size_t а не int32_t

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +int32_t CalcPrefixFunc(std::string& s, std::vector<int32_t>& prefix_func,
Три разных функции с названиями-вариациями слов calculate prefix func? Они явно делают не это.
Плюс опять const

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +    while(std::cin >> sym && sym != '_') {
Что за sym != '_'?

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +void PrefixFunc(std::string& pattern) {
const

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +            std::cout << cur_pos + 2 - pattern.size() << ' ';
Давай будем разделять обязанности "ввода-вывода" и решения задачи, давай?

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +    std::vector<int32_t> pattern_pref_func = CalcPrefixFunc(pattern);
Если не собираешься менять эту переменную, тоже const.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +        j = prefix_func[i - 1];
Почему переменная объявлена вне цикла но "ресетается" в начале каждой итерации? Это бан.

2019-09-29 16:19 UTC, Mrkol commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +    std::ios_base::sync_with_stdio(false);
В этой задаче хватит только std::cin.tie(nullptr)-костыля, этот не нужен.

2019-10-04 20:25 UTC, TopCoder2K commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +        }
имхо, но это бесполезный коммент, потому что я не понимаю, что значит уродливо, а что красиво в Вашем понимании

2019-10-04 20:34 UTC, TopCoder2K commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +        j = prefix_func[i - 1];
а не будет ли как-то неблагоприятно сказываться на времени работы создание каждый раз заново переменной внутри цикла?

2019-10-04 20:43 UTC, TopCoder2K commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +            std::cout << cur_pos + 2 - pattern.size() << ' ';
В той функции удобно сразу выводить. Если хранить значения и делать вывод в другой функции, то не будет O(p). Тогда паттерн ещё в этой функции считывать, чтобы было полноценный ввод/вывод?

2019-10-04 20:44 UTC, TopCoder2K commented on 3semester/Substr_by_prefix_func_1_1.cpp
> +    std::ios_base::sync_with_stdio(false);
Почему?

2019-10-05 16:53 UTC, TopCoder2K commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +    ~Node() = default;
Что конкретно?

2019-10-05 16:56 UTC, TopCoder2K commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +void ReconstructionByPrefix(std::string& answer) {
А что плохого в ссылках? Плюс мало ли компилятор RVO отрубит. Итераторы попробую припилить

2019-10-05 17:26 UTC, TopCoder2K commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +    std::vector<bool> alphabet(26,true);
Но работать стало, судя по тестам, в два раза дольше -_-

2019-10-05 18:16 UTC, TopCoder2K commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +class Node {
Я не знаю, как его ещё можно назвать.)

2019-10-05 18:17 UTC, TopCoder2K commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +    int32_t cur_z_value = 0, prefix_length = 0, prefix_remaining_length = 0;
А что в этом плохого? Можно переносить на новые строки, чтобы лучше читалось. Но не писать же 100 раз int32_t

2019-10-05 18:39 UTC, TopCoder2K commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +        ++counter;
почему, он там действительно играет роль счётчика

2019-10-05 18:41 UTC, TopCoder2K commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +void ReconstructionByZ(std::vector<Node>& answer) {
Вроде, убрал теперь

2019-10-05 18:43 UTC, TopCoder2K commented on 3semester/Reconstruction_by_z_func_1_3.cpp
> +            answer[counter] = answer[prefix_length - prefix_remaining_length];
нет, нет. Всегда вставлять первый элемент неверно.

2019-10-06 15:05 UTC, TopCoder2K commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +        }
if (!position) break;

2019-10-06 15:10 UTC, TopCoder2K commented on 3semester/Reconstruction_by_prefix_func_1_2.cpp
> +void ReconstructionByPrefix(std::string& answer) {
Избавляться от ссылок, всё ок

2019-10-06 19:21 UTC, closed without merging